config/routes.rb
OpenConferenceWare::Engine.routes.draw do
  get "/sign_in" => "authentications#sign_in", as: :sign_in
  get "/sign_out" => "authentications#sign_out", as: :sign_out

  match '/auth/:provider/callback' => 'authentications#create', via: :all
  get '/auth/failure' => 'authentications#failure'

  resources :authentications, only: [:create]

  resources :upload_files do
    collection do
      get 'download'
      get 'delete'
    end
  end
  resources :events do
    member do
      get :speakers
    end
    resources :proposals do
      collection do
        get :stats
      end
    end

    resources :tracks
    resources :session_types
    resources :rooms
    resources :schedule_items
    get '/sessions' => 'proposals#sessions_index', as: :sessions
    get '/sessions_terse' => 'proposals#sessions_index_terse', as: :sessions_terse
    get '/schedule' => 'proposals#schedule', as: :schedule
    get '/sessions/:id' => 'proposals#session_show', as: :session
    resources :selector_votes, only: :index
  end

  namespace :manage do
    resources :events
    resources :snippets
    get '/events/:id/proposals' => 'events#proposals', as: :event_proposals
    post '/events/:id/notify_speakers' => 'events#notify_speakers', as: :notify_speakers
  end

  resources :comments, only: [:index, :destroy]
  resources :proposals do
    resources :comments
    resource :selector_vote, only: :create
    get 'login' => 'proposals#proposal_login_required', as: :login
  end

  post '/proposals/manage_speakers/:id' => 'proposals#manage_speakers', as: :manage_proposal_speakers
  post '/proposals/search_speakers/:id' => 'proposals#search_speakers', as: :search_proposal_speakers
  post '/proposals/speaker_confirm/:id' => 'proposals#speaker_confirm', as: :speaker_confirm
  post '/proposals/speaker_decline/:id' => 'proposals#speaker_decline', as: :speaker_decline
  get '/sessions' => 'proposals#sessions_index', as: :sessions
  get '/schedule' => 'proposals#schedule', as: :schedule
  get '/sessions/:id' => 'proposals#session_show', as: :session
  get '/sessions_terse' => 'proposals#sessions_index_terse', as: :sessions_terse

  get '/' => 'proposals#proposals_or_sessions'
  get '/br3ak' => 'proposals#br3ak', as: :br3ak
  get '/m1ss' => 'proposals#m1ss', as: :m1ss

  resources :users, constraints: { id: /\w+/ } do
    member do
      get :complete_profile
      get :proposals
    end

    get 'favorites' => 'user_favorites#index', as: :favorites
    put 'favorites/modify' => 'user_favorites#modify', as: :modify_favorites
  end

  resources :session_types, only: [:index]
  resources :tracks, only: [:index]
  resources :rooms, only: [:index]
  resources :selector_votes, only: [:index]

  root to: 'open_conference_ware/events#index'
end

app/controllers/open_conference_ware/application_controller.rb
module OpenConferenceWare
  # Filters added to this controller apply to all controllers in the application.
  # Likewise, all the methods added will be available for all controllers.

  class ApplicationController < ActionController::Base

    helper :all # include all helpers, all the time

    # See ActionController::RequestForgeryProtection for details
    # Uncomment the :secret if you're not using the cookie session store
    protect_from_forgery # secret: '56b4f0ad244d35b7e0d30ba0c5e1ae61'

    # Provide methods for checking settings succinctly
    include SettingsCheckersMixin

    # Provide faux routes, e.g., #tracks_path
    include FauxRoutesMixin

    # Provide access to page_title in controllers
    include PageTitleHelper

    # Setup breadcrumbs
    include BreadcrumbsMixin
    add_breadcrumbs(OpenConferenceWare.breadcrumbs)

    # Filters
    before_filter :assign_events
    before_filter :assign_current_event_without_redirecting
    before_filter :log_the_current_user
    before_filter :log_the_session

    rescue_from ActionController::UnknownFormat do |e|
      render(text: 'Not Found', status: 404)
    end

    #---[ Authentication ]--------------------------------------------------

    # Store the given user in the session.
    def current_user=(new_user)
      session[:user_id] = (new_user.nil? || new_user.is_a?(Symbol)) ? nil : new_user.id
      @current_user = new_user
    end

    # Accesses the current user from the session.
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
      reset_session
    end
    helper_method :current_user

    # Returns true or false if the user is logged in.
    # Preloads @current_user with the user model if they're logged in.
    def logged_in?
      !!current_user
    end
    helper_method :logged_in?

    # Filter method to enforce a login requirement.
    def authentication_required
      logged_in? || access_denied(message: "Please sign in to access the requested page.")
    end

    # Redirect as appropriate when an access request fails.
    def access_denied(opts={})
      message = opts[:message] || "Access denied, please sign in with enough privileges to complete that operation."
      fallback_url = opts[:fallback_url] || opts[:fallback] || sign_in_path

      store_location
      redirect_to fallback_url, alert: message
    end

    # Store the URI of the current request in the session.
    #
    # We can return to this location by calling #redirect_back_or_default.
    def store_location(path=nil)
      session[:return_to] = path || request.fullpath
    end

    # Redirect to the URI stored by the most recent store_location call or
    # to the passed default.
    def redirect_back_or_default(default=nil)
      redirect_to(session[:return_to] || default || default_path)
      session[:return_to] = nil
    end
    alias_method :redirect_back_or_to, :redirect_back_or_default

    def default_path
      if @event
        if @event.proposal_status_published?
          event_sessions_path(@event)
        else
          event_proposals_path(@event)
        end
      else
        proposals_path
      end
    end

  protected

    #---[ General ]---------------------------------------------------------

    # Return the current User record or a nil if not logged in.
    def current_user_or_nil
      return(current_user.kind_of?(User) ? current_user : nil)
    end
    helper_method :current_user_or_nil

    # Return the current_user's email address, from either the currently-logged
    # in user or the cookie, else nil.
    def current_email
      return(current_user_or_nil.try(:email) || session[:email])
    end
    helper_method :current_email

    # Return a cache key for the currently authenticated or anonymous user.
    def current_user_cache_key
      return current_user_or_nil.try(:id) || -1
    end
    helper_method :current_user_cache_key

    # Return a cache key for the current event.
    def current_event_cache_key
      return @event.try(:id) || -1
    end
    helper_method :current_event_cache_key

    # Are we running in a development mode?
    def development_mode?
      return %w[development preview].include?(Rails.env)
    end
    helper_method :development_mode?

    def event_schedule?
      proposal_start_times? && proposal_statuses? && event_rooms?
    end
    helper_method :event_schedule?

    def schedule_visible?
      (@event.schedule_published? || admin?) && event_schedule?
    end
    helper_method :schedule_visible?

    # Flash notification levels allowed by #notify.
    NOTIFY_LEVELS = Set.new([:notice, :success, :failure])

    # Sets or appends the flash notification.
    #
    # Arguments:
    # * level: Symbol name of the notificaiton level, e.g. "failure".
    # * message: String message to display.
    def notify(level, message)
      level = level.to_sym
      raise ArgumentError, "Invalid flash notification level: #{level}" unless NOTIFY_LEVELS.include?(level)
      flash[level] = "#{flash[level]} #{message}".strip.html_safe
    end

    #---[ Access control ]--------------------------------------------------

    # Can the current user edit the current +record+?
    def can_edit?(record)
      raise ArgumentError, "No record specified" unless record

      if logged_in?
        if current_user.admin?
          true
        else
          # Normal user
          case record
          when Proposal
            # FIXME Add setting to determine if users can alter their proposals after the accepting_proposals deadline passed.
            ### accepting_proposals?(record) && record.can_alter?(current_user)
            record.can_alter?(current_user)
          when User
            current_user == record
          else
            raise TypeError, "Unknown record type: #{record.class}"
          end
        end
      else
        false
      end
    end
    helper_method :can_edit?

    # Is the current user an admin?
    def admin?
      logged_in? && current_user.admin?
    end
    helper_method :admin?

    def current_role
      (logged_in? && current_user.role) || :default
    end
    helper_method :current_role

    # Ensure user is an admin, or bounce them to the admin prompt.
    def require_admin
      admin? || access_denied(message: "You must have administrator privileges to access the requested page.")
    end

    def current_user_is_proposal_speaker?
      if logged_in?
        return @proposal.users.include?(current_user)
      end
      return false
    end
    helper_method :current_user_is_proposal_speaker?

    # Is this event accepting proposals?
    def accepting_proposals?(record=nil)
      event = \
        case record
        when Event then record
        when Proposal then record.event
        else @event
        end

      return event.try(:accepting_proposals?)
    end
    helper_method :accepting_proposals?

    def selector?
      logged_in? && current_user.selector?
    end
    helper_method :selector?

    def require_selector
      selector? || access_denied(message: "You must be part of the selection committee to access the requested page.")
    end

    #---[ Logging ]---------------------------------------------------------

    def log_the_current_user
      Rails.logger.info("User: #{current_user.id}, #{current_user.label}") if current_user_or_nil
    end

    def log_the_session
      Rails.logger.info("Session: #{session.to_hash.inspect}") if session.respond_to?(:data)
    end

    #---[ Assign items ]----------------------------------------------------

    # Assign an @events variable for use by the layout when displaying available events.
    def assign_events
      @events = Event.all
    end

    # Return the event and a status which describes how the event was assigned. The status can be one of the following:
    # * :assigned_to_param
    # * :invalid_param
    # * :invalid_proposal_event
    # * :assigned_to_current
    # * :empty
    def get_current_event_and_assignment_status
      invalid = false

      # Try finding event using params:
      event_id_key = controller_name == "events" ? :id : :event_id
      if key = params[event_id_key]
        if event = Event.find_by_slug(key)
          return [event, :assigned_to_param]
        else
          logger.info "error, couldn't find event from key: #{key}"
          invalid = :invalid_param
        end
      end

      # Try finding event using proposal:
      if controller_name == "proposals" && params[:id]
        if proposal = Proposal.find_by_id(params[:id])
          if proposal.event
            return [proposal.event, :assigned_to_param]
          else
            logger.info "error, couldn't find event from Proposal ##{proposal.id}"
            invalid = :invalid_proposal_event
          end
        end
      end

      # Try finding the current event.
      if event = Event.current
        logger.info "assigned to current event"
        if invalid
          return [event, invalid]
        else
          return [event, :assigned_to_current]
        end
      end

      logger.info "error, no current event found"
      return [nil, :empty]
    end

    # Assign @event if it's not already set. Also set the
    # @event_assignment value to describe how the @event was assigned,
    # which can be one of the following values:
    # * :assigned_already
    # * Or any of the statuses described in
    #   #get_current_event_and_assignment_status
    def assign_current_event_without_redirecting
      invalid_param = false

      # Only assign event if one isn't already assigned.
      if @event
        logger.info "already assigned"
        @event_assignment = :assigned_already
      else
        @event, @event_assignment = get_current_event_and_assignment_status()
      end
      return false
    end

    # Ensure that @event is assigned (by #assign_current_event_without_redirecting).

app/controllers/open_conference_ware/authentications_controller.rb
module OpenConferenceWare
  class AuthenticationsController < ApplicationController
    before_filter :require_auth_hash, only: [:create]

    # We need to accept a raw POST from an OmniAuth provider with no authenticity token.
    skip_before_filter :verify_authenticity_token, :only => :create

    def sign_in
      page_title "Sign In"
    end

    def sign_out
      cookies.delete :auth_token
      reset_session
      flash[:notice] = "You have been logged out."

      redirect_back_or_default
    end

    def create
      @authentication = Authentication.find_and_update_or_create_from_auth_hash(auth_hash)

      if @authentication.user
        self.current_user = @authentication.user
      elsif logged_in?
        @authentication.user = current_user
        @authentication.save
      else
        self.current_user = User.create_from_authentication(@authentication)
      end

      redirect_back_or_default
    end

    def failure
      flash[:error] = params[:message]
      redirect_to sign_in_path
    end

    protected

    def auth_hash
      request.env['omniauth.auth']
    end

    def require_auth_hash
      redirect_to(sign_in_path) and return unless auth_hash
    end
  end
end

app/controllers/open_conference_ware/comments_controller.rb
module OpenConferenceWare
  class CommentsController < ApplicationController

    SECRET = OpenConferenceWare.comments_secret

    MAX_FEED_ITEMS = 50

    before_filter :require_admin, except: [:index, :create]

    def index
      @comments = Comment.listable
      add_breadcrumb "Comments", comments_path()

      if [:atom, :json, :xml].include?(request.format.to_sym)
        unless params[:secret] == SECRET
          render(text: "403 Forbidden: You can't see the comments feed unless you supply the secret key", status: 403) and return
        end
        @comments = @comments[0..MAX_FEED_ITEMS]
      else
        if admin?
          respond_to do |format|
            format.html  # index.html.erb
            format.atom
          end
        else
          require_admin
        end
      end
    end

    # This is a weird action. The form is part of the proposals#show page, so errors and successes both go back to that page.
    def create
      if params[:quagmire].present?
        flash[:failure] = "Comment rejected because you're behaving like a robot, please leave the 'Leave blank' field blank."
        redirect_to(:back) rescue redirect_to proposals_path()
        return
      end

      @proposal = Proposal.find(params[:proposal_id])
      @comment = @proposal.comments.new(comment_params)

      # Use session to store email address and prefill it as needed
      if @comment.email.blank?
        @comment.email = current_email
      else
        session[:email] = @comment.email
      end

      respond_to do |format|
        if @comment.save
          flash[:success] = "Comment added."
          format.html { redirect_to(proposal_path(@comment.proposal, commented: true)) }
          format.xml  { render xml: @comment, status: :created }
          format.json { render json: @comment, status: :created }
        else
          @display_comment_form = true
          @focus_comment = true
          flash[:failure] = "Invalid comment."

          format.html { render template: "open_conference_ware/proposals/show" }
          format.xml  { render xml: @comment.errors, status: :unprocessable_entity }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
      flash[:success] = "Destroyed comment: #{@comment.id}"

      respond_to do |format|
        format.html {
          redirect_to(:back) rescue redirect_to(comments_path)
        }
      end
    end

  private

    def comment_params
      params.require(:comment).permit(:name, :email, :message)
    end

  end
end

app/controllers/open_conference_ware/events_controller.rb
module OpenConferenceWare
  class EventsController < ApplicationController
    include BreadcrumbsMixin
    add_breadcrumb "Events", "/events"

    before_filter :assert_current_event_or_redirect
    before_filter :normalize_event_path_or_redirect
    before_filter :assert_proposal_status_published, only: :speakers
    before_filter :require_admin, only: [:selector_votes]

    def index
      @events = Event.order("deadline asc")

      respond_to do |format|
        format.html
        format.json { render json: @events }
        format.xml  { render xml:  @events }
      end
    end

    def show
      respond_to do |format|
        format.html { redirect_to event_proposals_path(@event) }
        format.json { render json: @event }
        format.xml  { render xml:  @event }
      end
    end

    def speakers
      assign_prefetched_hashes

      respond_to do |format|
        format.html
        format.json { render json: @speakers }
        format.xml  { render xml:  @speakers }
        format.csv  { render csv:  @speakers, style: admin? ? :full : :public }
      end
    end
  end
end

app/views/open_conference_ware/users/_account_box.html.erb
<div id='account-box'>
  <%= link_to( image_tag( current_user.photo.url(:avatar), :class => 'user-photo photo' ), current_user ) if current_user.photo.file? %>
  <h3><%= link_to current_user.label, current_user %></h3>
  <div class='user_actions'>
    <% if user_profiles? %>
      <%= link_to "Edit profile", edit_user_path(current_user) %> |
    <% end -%>
    <%= link_to "Sign out", sign_out_path %>
  </div>
</div>

app/views/open_conference_ware/users/_block.html.erb
<%
# Display a user and their proposals/sessions with conditional formatting.
#
# Locals:
# * user => The User to display. REQUIRED.
# * wrapper_tag => Tag to wrap the display in. Defaults to :div.
# * display_sub_list => Should a sub_list, a detailed list of proposals/sessions for the user, be displayed? Defaults to false.
# * hide_rooms => Should the rooms be hidden in the list of sessions displayed for each user? Defaults to false.
# * only_for_event => Only display entries associated with this event record or its children. Optional.

hide_rooms ||= false
wrapper_tag ||= :div
display_sub_list ||= false
only_for_event = local_assigns[:only_for_event]
%>

<%= content_tag wrapper_tag, :class => "user_box vcard #{admin? && user.admin? ? ' admin' : ''}" do %>
  <%= link_to( image_tag( user.photo.url(:profile), :class => 'user-photo photo' ), user ) if user.photo.file? %>
  <div class='user_head'>
    <h3><%= link_to user.label, user, :name => "id_#{user.id}", :id => "id_#{user.id}", :class => 'fn n' %></h3>
    <% unless user.affiliation.blank? -%>
    <span class='affiliation org'><%= user.affiliation %></span>
    <% end -%>
  </div>
  <div class='user_body'>
    <div class='user_links'>
      <ul>
        <% if admin? || can_edit?(user) %>
          <li>Email (private): <%= display_link_to(user.email, :mailto => true) %></li>
        <% end -%>
        <% unless user.website.blank? %>
          <li>Website: <%= display_link_to(user.website, :nofollow => true, :class => 'url') %></li>
        <% end %>
        <% unless user.blog_url.blank? %>
          <li>Blog: <%= display_link_to(user.blog_url, :nofollow => true, :class => 'url') %></li>
        <% end %>
        <% unless user.twitter.blank? %>
          <li>Twitter: <%= display_link_to(user.twitter_url, :title => user.twitter, :nofollow => true, :class => 'url') %></li>
        <% end %>
        <% unless user.identica.blank? %>
          <li>Identi.ca: <%= display_link_to(user.identica_url, :title => user.identica, :nofollow => true, :class => 'url') %></li>
        <% end %>
        <% user_favorites_count = @user_favorites_count_for_user_hash ? (@user_favorites_count_for_user_hash[user.id] || 0) : user.favorites.count %>
        <% unless user_favorites_count == 0 %>
          <li>Favorites: <%= link_to "View #{user.first_name.try(:possessiveize)} favorites", user_favorites_path(user) %></li>
        <% end -%>
      </ul>
    </div>

  <% unless user.biography.blank? %>
    <h4>Biography</h4>
    <div class='note'>
      <%= display_textile_for user.biography %>
    </div>
  <% end %>

  <% if can_edit?(user) %>
    <div class='record-controls'>
      <%= link_to "Edit user", edit_user_path(user), :class => "editable" %>
    </div>
  <% end %>

  <% if display_sub_list %>
    <%= render :partial => 'open_conference_ware/proposals/sub_list', :locals => { :container => user, :header_tag => :h4 } %>
  <% else %>
    <% if @event.proposal_status_published? %>
      <%
      # Use prefetched values
      sessions = @sessions_for_user_hash.try(:fetch, user.id, nil) || user.sessions
      sessions = @event.related_proposals(sessions) if only_for_event
      %>
      <% unless sessions.empty? %>
        <h4 class='sessions'>Sessions</h4>
        <%= render :partial => 'open_conference_ware/proposals/list_concise', :locals => { :items => sessions, :hide_rooms => hide_rooms } %>
      <% end %>
    <% end -%>
  <% end -%>

  </div>
<% end -%>

app/views/open_conference_ware/users/_list.html.erb
<%
# Display a list of users and their sessions.
#
# Locals:
# * users => Array of users to display. REQUIRED.
# * hide_rooms => Should the rooms be hidden in the list of sessions displayed for each user? Defaults to false.
# * only_for_event => Only display entries associated with this event record or its children. Optional.

hide_rooms ||= false
only_for_event = local_assigns[:only_for_event]
%>

<ul class='user_list'>
<% users.each do |user| %>
  <%= render :partial => 'open_conference_ware/users/block', :locals => { :user => user, :wrapper_tag => :li, :hide_rooms => hide_rooms, :only_for_event => only_for_event } %>
<% end -%>
</ul>

app/views/open_conference_ware/users/edit.html.erb
<% page_title "Edit user: #{h @user.label}" %>

<%= form_for(@user, :html => {:multipart => true}) do |f| %>
  <%= f.error_messages %>
  <%= hidden_field_tag :require_complete_profile, true if params[:require_complete_profile] %>

  <% if admin? %>
    <div class="checkbox">
      <label><%= f.check_box :admin %> Admin?</label>
    </div>
    <div class="checkbox">
      <label><%= f.check_box :selector %> Selection committee?</label>
    </div>
    <div class="checkbox">
      <label><%= f.check_box :complete_profile %> Complete profile?</label>
    </div>
  <% end %>
  <% if admin? || can_edit?(@user) %>
    <div class="form-group">
      <label><%= required_field if @user.complete_profile %>Email (kept private)</label>
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  <% end %>
  <div class="form-group">
    <label><%= required_field if @user.complete_profile %>First Name</label>
    <%= f.text_field :first_name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <label><%= required_field if @user.complete_profile %>Last Name</label>
    <%= f.text_field :last_name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <label>Affiliation</label>
    <%= f.text_field :affiliation, :class => "form-control" %>
  </div>
  <div class="form-group">
    <label>Website URL</label>
    <%= f.text_field :website, :class => "form-control" %>
  </div>
  <div class="form-group">
    <label>Blog URL</label>
    <%= f.text_field :blog_url, :class => "form-control" %>
  </div>
  <div class="form-group">
    <label>Twitter handle</label>
    <%= f.text_field :twitter, :class => "form-control" %>
  </div>
  <div class="form-group">
    <label>Identi.ca handle</label>
    <%= f.text_field :identica, :class => "form-control" %>
  </div>
  <div class="form-group">
    <label>Photo</label>
    <%= image_tag @user.photo.url(:avatar) if @user.photo.file? %>
    <%= f.file_field :photo %>
  </div>
  <div class="form-group">
    <label><%= required_field if @user.complete_profile %>Biography</label> (<%= display_textile_help_link %>)
    <%= f.text_area :biography, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit("Save my profile", :class => "btn btn-primary") %>
    <%= f.submit("Complete my speaker profile...", :name => :require_complete_profile, :class => "btn btn-default") unless @user.complete_profile? %>
    <%= link_to "Cancel", @user, :class => "btn btn-default" %>
    <% if admin? %>
      <%= link_to "Delete", @user, :method => :delete, :data => { :confirm => "Delete user #{h @user.label}?" }, :class => "btn btn-danger pull-right" %>
    <% end %>

    <p style="margin-top: 2em; margin-bottom: 0">
      <%= required_field %> Fields marked with a red asterisk required and must be filled.
    </p>
  </div>
<% end %>

app/views/open_conference_ware/users/index.html.erb
<% page_title "Users" %>

<div id="user-index">
  <table class="scaffolded">
    <tr>
      <th>Name</th>
      <% if admin? %>
        <th>Actions</th>
      <% end %>
    </tr>
    <% @users.each do |user| -%>
    <tr class="<%= cycle('odd', 'even') %>">
      <td>
        <% if admin? && user.admin? %>
          (<strong class='admin'>admin</strong>)
        <% end %>
        <%= link_to(user.label, user_path(user)) %><%= (", " + user.affiliation) unless user.affiliation.blank? %>
      </td>
      <% if admin? %>
        <td nowrap="nowrap">
          <%= link_to "Edit", edit_user_path(user), :class => "editable" %>
          <%= link_to "Delete...", user, :method => :delete, :data => { :confirm => "Delete user #{h user.label}?" }, :class => "deletable" %>
        </td>
      <% end %>
    </tr>
    <% end -%>
  </table>
</div>

app/views/open_conference_ware/users/new.html.erb
<%= error_messages_for :user %>
<%= form_for :user, :url => users_path do |f| -%>
  <p><label for="email">Email</label><br/>
  <%= f.text_field :email %></p>

  <p><%= submit_tag 'Sign up' %></p>
<% end -%>

app/views/open_conference_ware/users/proposals.html.erb
<% is_for_current_user = (current_user == @user) %>
<% cache "my_proposals,user_#{@user.id},is_me_#{is_for_current_user}" do %>
  <% page_title "#{@user.label.possessiveize} Proposals"%>
  <% unless @proposals.blank? %>
    <% @proposals.group_by(&:event).sort_by{|group| group[0].start_date || 0}.reverse.each do |event, proposals| %>
      <% if event.proposal_status_published? %>
        <% unless ( sessions = proposals.select{|proposal| proposal.confirmed?} ).empty? %>
          <h2>Sessions accepted for <%= event.title %></h2>
          <%= render :partial => "open_conference_ware/proposals/list", :locals => {:kind => :sessions, :records => sessions, :sorter => false} %>
        <% end -%>

        <% unless ( unaccepted_proposals = proposals.reject{|proposal| proposal.confirmed? } ).empty? %>
          <h2>Sessions proposed for <%= event.title%></h2>
          <%= render :partial => "open_conference_ware/proposals/list", :locals => {:kind => :proposals, :records => unaccepted_proposals, :sorter => false} %>
        <% end -%>
      <% else -%>
        <h2>Sessions proposed for <%= event.title%></h2>
        <%= render :partial => "open_conference_ware/proposals/list", :locals => {:kind => :proposals, :records => proposals, :sorter => false} %>
      <% end -%>
    <% end -%>
  <% else -%>
    <h2><%= is_for_current_user ? 'You have' : "#{@user.label} has" %> not submitted any proposals</h2>
  <% end -%>
<% end -%>

app/views/open_conference_ware/users/show.html.erb
<% page_title @user.label %>

<% cache "user_#{@user.id},edit_#{can_edit?(@user)}" do %>
  <%= render :partial => 'open_conference_ware/users/block', :locals => { :user => @user, :display_sub_list => true } %>
<% end %>